- .gitignore
- Gemfile
- Gemfile.lock
- app/assets/javascripts/editor.js
- app/assets/javascripts/turtle.js
- app/controllers/exercises_controller.rb
- app/controllers/submissions_controller.rb
- app/views/exercises/_editor.html.slim
- app/views/exercises/_form.html.slim
- app/views/exercises/implement.html.slim
- app/views/exercises/show.html.slim
- config/docker.yml.erb
- config/locales/de.yml
- config/locales/en.yml
- db/migrate/20150922125415_add_hide_file_tree_to_exercises.rb
- db/schema.rb
- lib/docker_client.rb
- lib/py_unit_adapter.rb
- webpython/Dockerfile
- webpython/Makefile
- webpython/README.md
- webpython/assess.py
- webpython/turtle.py
- webpython/webpython.py
Change Run from ServerSendEvents to Websockets
Some minor UI changes and additional features
> Webpython hybrid

- app/assets/javascripts/dashboard.js
> Fix leaking interval creating potentially unlimited unwanted requests

- app/views/exercises/_file_form.html.slim
- app/views/exercises/_form.html.slim
- app/views/exercises/show.html.slim
This uses Bootstrap's collapse feature to de-clutter files in exercise details.
> Collapse files

- app/assets/javascripts/editor.js.erb
- app/assets/stylesheets/editor.css.scss
- app/controllers/comments_controller.rb
- app/controllers/request_for_comments_controller.rb
- app/models/external_user.rb
- app/models/internal_user.rb
- app/models/request_for_comment.rb
- app/policies/comment_policy.rb
- app/views/application/_session.html.slim
- app/views/exercises/_editor.html.slim
- app/views/exercises/_editor_file_tree.html.slim
- app/views/exercises/_editor_frame.html.slim
- app/views/exercises/_request_comment_dialogcontent.html.slim
- app/views/request_for_comments/index.html.slim
- app/views/request_for_comments/show.html.erb
- config/locales/de.yml
- config/locales/en.yml
- db/migrate/20160426114951_add_question_to_request_for_comments.rb
- db/schema.rb
Reworked request for comments handling.
> Request for comments enhancements

- provision.sh
revised provison file to pull the right docker images required.
> edit provision script to pull the new images required

- app/controllers/code_ocean/files_controller.rb
- app/controllers/exercises_controller.rb
- app/models/code_ocean/file.rb
- app/views/exercises/_editor_file_tree.html.slim
- app/views/exercises/_form.html.slim
- app/views/exercises/show.html.slim
- config/locales/de.yml
- config/locales/en.yml
- db/migrate/20160510145341_add_allow_file_creation_to_exercises.rb
- db/schema.rb
This pull request allows to define a boolean flag "allow file creation" for exercises and fixes the creation of files with the same name in the editor.
> Fix file creation behavior

- app/views/exercises/index.html.slim
This should fix #60. Please check with a current database dump.
> Don't call author policy if author is missing

- app/views/exercises/_editor.html.slim
- app/views/exercises/_file_form.html.slim
- app/views/exercises/show.html.slim
Now files are not automatically collapsed and sorted
> Collapsing change + sorted alphabetically

- app/assets/javascripts/editor/editor.js.erb
- app/controllers/execution_environments_controller.rb
- app/controllers/exercises_controller.rb
- app/controllers/external_users_controller.rb
- app/models/exercise.rb
- app/views/exercises/_request_comment_dialogcontent.html.slim
- config/locales/de.yml
- config/locales/en.yml
do not show more than 2 interventions per day
> do not show interventions on solved exercises, reduce to 2 interventions per day

- app/assets/stylesheets/request-for-comments.css.scss
- app/controllers/request_for_comments_controller.rb
- app/mailers/user_mailer.rb
- app/models/request_for_comment.rb
- app/models/submission.rb
- app/policies/request_for_comment_policy.rb
- app/views/request_for_comments/show.html.erb
- app/views/user_mailer/send_thank_you_note.slim
- config/locales/de.yml
- config/locales/en.yml
- config/routes.rb
- db/migrate/20170608141612_add_thank_you_note_to_request_for_comments.rb
- db/schema.rb
Adds a small dialog to send a thank you note to all users who helped answer a request for comments.
> Rfc mark as answered extensions

- app/assets/javascripts/file_templates.js.coffee
- app/views/application/_flash.html.slim
- lib/assets/javascripts/flash.js
- lib/assets/stylesheets/flash.css.scss
This adds a button to close a flash message.
> Close flash messages

- app/assets/javascripts/editor/submissions.js.erb
Update "last saved at" label after all types of submissions, not only autosaves
> Update Save Label

- app/assets/stylesheets/request-for-comments.css.scss
- app/controllers/comments_controller.rb
- app/models/comment.rb
- app/policies/comment_policy.rb
- app/views/comments/index.json.jbuilder
- app/views/request_for_comments/show.html.erb
- config/locales/de.yml
- config/locales/en.yml
Use popovers with markup instead of tooltips.
> Cleaner RFC comments

- app/controllers/request_for_comments_controller.rb
- app/views/application/_session.html.slim
- app/views/request_for_comments/index.html.slim
- config/locales/de.yml
- config/locales/en.yml
- config/routes.rb
View RFCs that the user has commented on, ordered by last activity (other comments)
> Rfc enhancements

- app/controllers/exercises_controller.rb
- app/views/exercises/_form.html.slim
- app/views/exercises/index.html.slim
- app/views/exercises/show.html.slim
- config/locales/de.yml
- config/locales/en.yml
- db/migrate/20171002131135_remove_expected_working_time.rb
- db/schema.rb
> removed expected working time from show/create/index of exercises

- app/controllers/concerns/submission_scoring.rb
- app/controllers/request_for_comments_controller.rb
- app/models/request_for_comment.rb
- app/views/request_for_comments/index.html.slim
- db/migrate/20180130172021_add_reached_full_score_to_request_for_comment.rb
- db/schema.rb
RFCs now represent if the participant asking for help reached full score in the meantime.
> Rfc soft solved

- app/controllers/exercises_controller.rb
- db/migrate/20180202132034_add_times_featured_to_request_for_comments.rb
- db/schema.rb
> add times_featured to rfc

- Vagrantfile
- provision.sh
Also, some commands were only available in an interactive shell, those were changed.
> Update Vagrant provision.sh to execute command as non-root user

- Gemfile
- Gemfile.lock
Use slim and js for rails g and remove now unused coffee-rails dependency
> Caffeine withdrawal

- app/assets/stylesheets/request-for-comments.css.scss
- app/views/request_for_comments/show.html.erb
> Parse rfc run output

- app/assets/stylesheets/statistics.css.scss
- app/controllers/exercises_controller.rb
- app/views/exercises/external_users/statistics.html.slim
- config/locales/de.yml
- config/locales/en.yml
> Highlight worktime gaps

- app/assets/javascripts/exercises.js.erb
- app/views/exercises/_file_form.html.slim
> fix deleting files from exercise edit

- app/assets/javascripts/editor/editor.js.erb
- app/assets/stylesheets/exercises.css.scss
- app/views/exercises/implement.html.slim
- config/locales/de.yml
- config/locales/en.yml
Style exercise description as a card and display an additional (more obvious) toggle.
> Experimental exercise description design

- app/views/application/_navigation.html.slim
- app/views/application/_navigation_submenu.html.slim
- app/views/layouts/application.html.slim
This should reduce rendering time for the navigation menu in production.
> Cache rendered navigation templates

- app/helpers/lti_helper.rb
- db/migrate/20180823135317_add_index_for_testrun_submission_id.rb
- db/schema.rb
1. Add index on testrun.submissionId
2. replace lti_parameters.size with lti_parameters.present? to prevent COUNT query
> Performance Optimizations:

- app/controllers/remote_evaluation_controller.rb
- app/controllers/submissions_controller.rb
- app/models/remote_evaluation_mapping.rb
- db/migrate/20181126163428_add_user_type_to_remote_evaluation_mappings.rb
- db/schema.rb
Otherwise, the download of submissions no longer works in Rails 5
> Specify `ExternalUser` as class for `user` in `RemoteEvaluationMapping`

- app/assets/javascripts/exercises.js.erb
- app/views/exercises/_file_form.html.slim
Prevent hidden selection field from being removed after cloning the dummy. Also ensure the caret looks nice and add the file extension if possible.
> Fix adding files to exercises (as admin)

- app/controllers/proxy_exercises_controller.rb
- app/models/proxy_exercise.rb
- app/views/proxy_exercises/_form.html.slim
- app/views/proxy_exercises/index.html.slim
- app/views/proxy_exercises/show.html.slim
- db/migrate/20181119161514_add_user_to_proxy_exercise.rb
- db/schema.rb
- spec/factories/proxy_exercise.rb
This is required for the existing policies to work
> Add user (ID and type) to proxy exercise

- app/models/request_for_comment.rb
Inlining the code did not turn out well, as we have to cope with the polymorphic association of user here..
> fix active record induced error on postgres by removing distinct.

- app/models/exercise.rb
- app/views/exercise_collections/statistics.html.slim
- config/locales/de.yml
- config/locales/en.yml
- spec/models/exercise_spec.rb
Added a table to the exercise_collections_statistics view
> enhance exercise_collection_statistics

- README.md
- db/seeds.rb
- spec/db/seeds_spec.rb
During the setup of a codeocean instance for my development environment I had some issues while seeding the database. 
This PR fixes the two main issues I encountered.
> Improve provision instructions

- app/assets/javascripts/editor/editor.js.erb
> Reenable rfc timelimit

- app/policies/exercise_policy.rb
- app/policies/proxy_exercise_policy.rb
- app/views/exercises/external_users/statistics.html.slim
- app/views/exercises/feedback.html.slim
- app/views/exercises/statistics.html.slim
- config/locales/de.yml
- config/locales/en.yml
- spec/policies/exercise_policy_spec.rb
* Hide non-public exercises and proxy exercises
* Hide average working time value on statistic page
* Add hint about filter to submission page for teachers
* Hide display name from feedback page
> Adjust teacher permissions

- app/controllers/concerns/lti.rb
> Remove teacher access for informatiktag2020

- app/controllers/concerns/submission_scoring.rb
- app/controllers/exercises_controller.rb
- lib/python20_course_week.rb
- lib/user_group_separator.rb
Tele-approved by @rteusner :+1:
> Prepare Python20 Course Experiments

- app/controllers/concerns/submission_scoring.rb
Tele-approved by @rteusner :+1:
> Concurrent scoring

- lib/py_lint_adapter.rb
Tele-approved by @rteusner :+1:
> Add filename to PyLint Adapter

- app/controllers/concerns/submission_scoring.rb
- app/models/linter_check.rb
- app/models/linter_check_run.rb
- app/models/submission.rb
- db/migrate/20201026184633_create_linter_checks.rb
- db/schema.rb
- lib/py_lint_adapter.rb
Specifically optimized for PyLint
> Store Linter Run Assessment

- app/assets/javascripts/editor/editor.js.erb
- app/controllers/submissions_controller.rb
- docs/LOCAL_SETUP.md
- lib/assessor.rb
- lib/python20_course_week.rb
This PR is a collection of small changes
> Miscellaneous changes

- config/initializers/rails_admin.rb
limits the pagination to fix performance problems
(Does not show total number of files and pages anymore)
> rails_admin: limit pagination for files 

- Vagrantfile
- config/action_mailer.yml.example
- config/docker.yml.erb.ci
- config/docker.yml.erb.example
- config/puma.rb
- db/seeds/development.rb
- docs/LOCAL_SETUP.md
- docs/webpython/README.md
* Adds a new default consumer in dev environment for hassle-free setup with Xikolo
* Change the default port in dev environment to 3333 (already using that for a long time).
> Improve LTI dev environment

- README.md
- docs/LOCAL_SETUP.md
Also small addition in readme for port binding
> Changes in local setup readme to make docker cfg upgrade-safe

- app/assets/javascripts/editor/editor.js.erb
- app/controllers/exercises_controller.rb
- app/views/exercises/_editor.html.slim
- app/views/interventions/_tips_intervention_modal.html.slim
- config/locales/de.yml
- config/locales/en.yml
- db/migrate/20211114145024_create_tips_intervention.rb
- db/schema.rb
- lib/java21_study.rb
- lib/user_group_separator.rb
This MR:
- adds tips interventions
- adds A/B/n test setup for Java2021 course
- enables break interventions
> Add tips intervention for Java2021 course

- app/assets/javascripts/community_solution.js
- app/assets/javascripts/editor/editor.js.erb
- app/assets/javascripts/editor/submissions.js
- app/assets/stylesheets/editor.css.scss
- app/controllers/community_solutions_controller.rb
- app/controllers/concerns/file_parameters.rb
- app/controllers/concerns/redirect_behavior.rb
- app/controllers/exercises_controller.rb
- app/models/community_solution.rb
- app/models/community_solution_contribution.rb
- app/models/community_solution_lock.rb
- app/policies/community_solution_policy.rb
- app/views/community_solutions/_form.html.slim
- app/views/community_solutions/edit.html.slim
- app/views/community_solutions/index.html.slim
- app/views/exercises/_editor.html.slim
- app/views/exercises/_editor_frame.html.slim
- app/views/interventions/_tips_intervention_modal.html.slim
- app/views/layouts/application.html.slim
- config/locales/de.yml
- config/locales/en.yml
- config/routes.rb
- db/migrate/20211114145024_create_tips_intervention.rb
- db/migrate/20211118185051_create_community_solution.rb
- db/schema.rb
- lib/java21_study.rb
- lib/user_group_separator.rb
This MR:
- adds support for community solutions
- slightly refactors some Javascript and Ruby modules
- database model for CommunitySolution
> Add community solution

- provision/provision.vagrant.sh
> Use PostgreSQL version in Vagrant script

- app/assets/javascripts/exercises.js.erb
- app/models/file_type.rb
- app/services/proforma_service/convert_task_to_exercise.rb
- db/migrate/20230206203117_migrate_filetype_extensions_not_nil.rb
- db/schema.rb
- spec/factories/file_type.rb
- spec/models/file_type_spec.rb
- spec/services/proforma_service/convert_task_to_exercise_spec.rb
> fix file_type selection for Makefile

- app/assets/javascripts/base.js
- app/assets/javascripts/channels/synchronized_editor_channel.js
- app/assets/javascripts/programming_groups.js
- app/models/programming_group.rb
- app/views/exercises/_editor.html.slim
- app/views/exercises/implement.html.slim
- app/views/layouts/application.html.slim
- app/views/programming_groups/_form.html.slim
- app/views/programming_groups/_info_pair_programming.html.slim
- app/views/programming_groups/new.html.slim
- config/locales/de.yml
- config/locales/en.yml
* Add info modal for pair programming
* Improve layout for programming groups
> Layout improvements  & Info for pair programming

- app/assets/javascripts/channels/synchronized_editor_channel.js
- app/assets/javascripts/editor/editor.js.erb
- app/assets/javascripts/editor/submissions.js
- app/channels/synchronized_editor_channel.rb
- app/models/event/synchronized_editor.rb
- config/locales/de.yml
- config/locales/en.yml
- db/migrate/20230912162208_require_session_id_for_event_synchronized_editor.rb
- db/schema.rb
* Replaces compareDeltaObjects with editor.curOp
* Reload text for person joining pp session
* Generate Session ID on server for synchronized editor
* Synchronize resetCode for pair programming
> Refactor pair programming & solve problems with synchronization

- Gemfile
- Gemfile.lock
- lib/runner/backend-output.schema.json
- spec/lib/runner/strategy/poseidon/connection_spec.rb
that included a wrong usage of the `required` attribute.
See #1914 and openHPI/poseidon#456.
> Fix Poseidon JSON schema

- app/controllers/exercises_controller.rb
Fixes [CODEOCEAN-12D](https://codeocean.sentry.io/issues/5054304821/)
> Fix invalid column reference for non-detailed exercise statistics

- app/views/exercises/external_users/statistics.html.slim
- spec/features/external_user_statistics_spec.rb
This PR fixes two minor issues I noticed during my final check on #2288:
- 77f0c5d2: Add missing parentheses to external user statistics slider
- bbd37b5b: Fix JavaScript error for ExternalUserStatistics
> Fix External User Statistics

- app/mailers/user_mailer.rb
- app/views/user_mailer/exercise_anomaly_detected.html.slim
- config/locales/de/mailers/user_mailer.yml
- config/locales/en/mailers/user_mailer.yml
- lib/tasks/detect_exercise_anomalies.rake
With this PR, the last mailers get updated with the AuthenticationToken, finally removing the hints in emails about potential errors.
💁 The anomaly detection is a prior research experiment by a former PhD student and the code could benefit from a major refactoring and unit testing. This is out of scope for the current fix.
> Fix anomaly detection and introduce AuthenticationToken

- app/views/execution_environments/_form.html.slim
- app/views/execution_environments/shell.html.slim
- app/views/internal_users/_form.html.slim
- app/views/internal_users/activate.html.slim
- app/views/internal_users/forgot_password.html.slim
- app/views/internal_users/reset_password.html.slim
- app/views/sessions/new.html.slim
I got annoyed by the wrong autocomplete of my browser, so I added autocomplete annotations:
* Disable autocomplete and spellcheck for commands
* Add authentication hints
> Add autocomplete hints

- config/puma.rb
Related to [codeocean-terraform!200](https://lab.xikolo.de/codeocean/codeocean-terraform/-/merge_requests/200#note_214062)
> Disable Puma stdout/stderr redirection

- Gemfile.lock
- yarn.lock
Fixes CVE-2024-47764
Fixes GHSA-pxg6-pf52-xh8x
> Bundle Update
