app/views/request_for_comments/show.html.erb

Fixes Firefox support for the comment popup (cf. https://open.hpi.de/courses/javawork2016/question/b992d910-e40c-4643-bd21-f9a1fe9c7cb3 third comment).

Fix click event for compatibility

---

app/views/exercises/index.html.slim

Don't call (failing) policy selection if the exercise has no execution_environment

---

app/assets/javascripts/editor/editor.js.erb

otherwise we lose track of the time between opening the exercise and the first submission

creates an autosave submission on opening of the editor. 

---

app/assets/stylesheets/request-for-comments.css.scss
app/controllers/comments_controller.rb
app/controllers/subscriptions_controller.rb
app/views/exercises/_comment_dialogcontent.html.slim
db/migrate/20170920145852_add_deleted_to_subscription.rb
db/schema.rb

- subscriptions are insert-only; if `deleted`==`false`, `updated_at` is the deletion date.
- there will only be one notification per user, even if there is more than one subscription for this user
- the subscription box is now always visible (not only if someone commented before opening the modal)

Better Subscriptions

---

Gemfile
Gemfile.lock
config/deploy.rb
db/migrate/20180222145909_fix_timestamps_on_feedback.rb
db/schema.rb

fixed several severe bugs, that were still in the version update-gemfile.
One resulted in a segmentation fault on debian, the other one prevented lti sign-ins.
deployment was also broken and was fixed with an recursive flag.
And we fixed the feedback timestamps (removed default that overwrote correct timestamps)

Fix feedback timestamps

---

db/migrate/20180130172021_add_reached_full_score_to_request_for_comment.rb
db/migrate/20180222145909_fix_timestamps_on_feedback.rb

* migrate RFC-attributes in batches of 1000 to [save memory](https://rubyinrails.com/2017/11/16/use-find-each-instead-of-all-each-in-rails/)
* make migrations (at least pseudo-) reversible

Migration fixes

---

app/assets/javascripts/editor/editor.js.erb
app/assets/javascripts/editor/execution.js.erb
app/assets/stylesheets/editor.css.scss
app/controllers/concerns/submission_scoring.rb
app/controllers/submissions_controller.rb
app/models/structured_error.rb
app/views/error_templates/_form.html.slim
app/views/exercises/_editor_output.html.slim
config/locales/de.yml
config/locales/en.yml

Error hints

---

app/assets/javascripts/editor/editor.js.erb
app/assets/javascripts/editor/execution.js.erb
app/assets/javascripts/editor/websocket.js.erb
config/docker.yml.erb.example
config/docker.yml.erb.travis

IE11/Edge does not allow the trailing slash in the `protocol` property of a `URL` object, resulting in a silent fallback to `http` when opening up the websocket connection (in [execution.js.erb:7](https://github.com/openHPI/codeocean/blob/master/app/assets/javascripts/editor/execution.js.erb#L7)).
**Deployed configs should be adjusted as well** (even though the additional check in `editor/execution.js` technically makes this unnecessary).

Edge compat

---

lib/docker_client.rb

Close socket from container to server when killing the container in order to save run output

Parse runtime output on stop

---

app/assets/javascripts/editor/editor.js.erb
lib/assets/javascripts/url.js

Basic run/submit flow should now work with IE 10 and 11. Same as in Edge, Internet Explorer raises an error when closing the websocket connection. We currently ignore this.

IE url polyfill

---

app/models/code_ocean/file.rb
app/views/exercises/show.html.slim

This makes the order of test files consistent and useful. I need this in the ruby course (starting tomorrow) to provide helpful feedback with each test file, which are meant to guide users to the complete solution, step by step.
Explicit ordering in the view (!) is now no longer necessary.
**Questions for reviewers:**
- Could this have (unwanted) side effects in other places where files (e.g. by users) are listed?

Order files by name by default

---

app/assets/javascripts/editor/submissions.js.erb

Add the missing dot to call `replace` on `filename`.
Fixes #218.

Fix missing dot (fixes #218)

---

app/assets/javascripts/editor/editor.js.erb
app/assets/javascripts/editor/participantsupport.js
app/assets/javascripts/editor/submissions.js
app/assets/javascripts/error_templates.js

Reenables users to reset their exercise implementation to the original version
The problem laid in old methods used from jQuery versions prior to 1.8 (which was released on August 9, 2012)
> Deprecation Notice from jQuery docs:
> 
> The jqXHR.success(), jqXHR.error(), and jqXHR.complete() callbacks will be deprecated in jQuery 1.8. To prepare your code for their eventual removal, use jqXHR.done(), jqXHR.fail(), and jqXHR.always() instead.

Migrate jQuery function use for ajax in case of success or failure

---

config/initializers/docker.rb

Otherwise, the rake task might fail if the database connection could not be established (e.g. when creating a new database).

Prevent creation of the Docker containers if just running a db rake task

---

app/models/testrun.rb

(no file is present for `run` but e.g. for `assess`)

Specify file as optional for testruns

---

app/mailers/user_mailer.rb
app/models/external_user.rb
app/views/application/welcome.html.slim
app/views/exercise_collections/show.html.slim
app/views/exercises/feedback.html.slim
app/views/external_users/index.html.slim
app/views/external_users/show.html.slim
app/views/user_exercise_feedbacks/index.html.slim
app/views/user_mailer/send_thank_you_note.slim
spec/features/authentication_spec.rb

These changes should prevent undesired access on empty names or empty email addresses. We might consider changing the pseudo_name to something cool, e.g. by using the [Faker](https://github.com/stympy/faker) gem or the already integrated [Forgery](https://github.com/sevenwire/forgery) gem.
We might also discuss why the display name has been introduced and in which situations not to use it (as I did for `external_user/show`).

Consider empty name and mail for external users

---

app/controllers/concerns/lti.rb
app/controllers/study_groups_controller.rb
app/models/consumer.rb
app/policies/study_group_policy.rb
app/views/application/_navigation.html.slim
app/views/internal_users/index.html.slim
app/views/proxy_exercises/show.html.slim
app/views/study_groups/_form.html.slim
app/views/study_groups/edit.html.slim
app/views/study_groups/index.html.slim
app/views/study_groups/show.html.slim
config/locales/de.yml
config/locales/en.yml
config/routes.rb

As discussed for #245 
Teachers are now enabled to rename groups, however, we can't automatically get the course name as this resource is JWT-protected.

Improve groups with a view and always create a group

---

Gemfile
Gemfile.lock
app/controllers/concerns/lti.rb
app/controllers/submissions_controller.rb
app/views/exercises/_editor_file_tree.html.slim
provision.sh

As required for Monday, this PR adds support for another LTI option to disallow downloading exercises and submissions.
Further, this PR also updates the bundle to the newest versions where available.

Disable download

---

app/policies/exercise_policy.rb
spec/policies/exercise_policy_spec.rb

fixes #765 
Added a check to determine if a user actually has the codeharbor_link configured before offering the export.

Fix codeharbor-export policies

---

app/controllers/concerns/submission_scoring.rb
app/models/linter_check_run.rb
config/locales/de.linter.yml
lib/assessor.rb
lib/py_lint_adapter.rb
lib/py_unit_and_py_lint_adapter.rb
spec/helpers/yaml_spec.rb

This PR adds a framework that allows translating results from PyLint to German for a beginner MOOC in Python.
Each possible message, identified by its severity and name, has its own regex to search the output and a replacement string referring to the named capture groups of the regex. Very few possible linter results, such as `bad-whitespace` or `syntax-error` required additional processing and more translations due to a large number of possible values.
If for whatever reason, a translation cannot be found, an error will be logged for the administrators and the original result will be returned.
**Please have a look at the different German translations, which will be used dynamically** -- Thanks!
Below are some examples of translations and a screenshot for your convenience
--- …

Add German translations for PyLint adapter

---

config/initializers/rails_admin.rb

The Dashboard is suspected to have performance problems.
Disable it.
@MrSerth are you able to see what kind of queries cause the slowdown on production? I also remember reading something about n+1 queries during the authorization checks and I can imagine that there are quite a few users in CO

disable rails_admin dashboard

---

app/controllers/codeharbor_links_controller.rb
app/policies/codeharbor_link_policy.rb
config/code_ocean.yml.ci
config/code_ocean.yml.example
config/locales/de.yml
config/locales/en.yml
spec/controllers/codeharbor_links_controller_spec.rb
spec/policies/codeharbor_link_policy_spec.rb

This PR adds a config option to disable and enable CodeHarbor links platform-wide. If disabled, any access to views is prevented with Pundit and will raise a `NotAuthorizedException`.
⚠️  Please ensure to adapt your `code_ocean.yml` config accordingly. The new `[:codeharbor][:enabled]` setting is required. 
This PR also fixes the tests to ensure they work independently of the config option and improves some translations for CodeHarbor links.

Introduce new option for CodeHarbor

---

config/initializers/prometheus.rb
lib/prometheus/controller.rb

* Exclude Prometheus integration for rake tasks
* Query database for the count of RfCs with comments
* Postpone parallelization of Prometheus initialization

Improve Prometheus integration

---

app/assets/javascripts/editor/editor.js.erb
app/assets/javascripts/editor/submissions.js
app/assets/stylesheets/base.css.scss
app/assets/stylesheets/editor.css.scss
app/controllers/code_ocean/files_controller.rb
app/views/exercises/_editor.html.slim
app/views/exercises/_editor_button.html.slim
app/views/exercises/_editor_file_tree.html.slim
app/views/exercises/_editor_frame.html.slim
app/views/exercises/_editor_output.html.slim
lib/file_tree.rb
spec/lib/file_tree_spec.rb

This MR:
* Removes the "Files" folder from the File Tree
* Moves all buttons from the action sidebar to some other places, mostly the File Tree
* If the file tree is hidden, the download button is shown below the editor (bottom-left)
* Reset this file is not in the bottom-right corner below the editor
* Increases the transition speed when collapsing or expanding the sidebars
* Reduces the weight of the collapse and expand buttons (left and right sidebar)
Our goal was to make some space for the exercise description which might be moved to the left sidebar.
Old view:
New view:

Rebrush action sidebar for implement view

---

db/migrate/20180815115351_remove_event_indices.rb
db/schema.rb

When testing #1079, I noticed an issue when starting with an empty database during the application of all migration steps. This PR fixes the issue and regenerates the schema.rb to reflect the current framework changes.

Fix issues when migrating empty database

---

app/controllers/execution_environments_controller.rb
app/models/execution_environment.rb
app/models/runner.rb
lib/runner/strategy.rb
lib/runner/strategy/docker_container_pool.rb
lib/runner/strategy/null.rb
lib/runner/strategy/poseidon.rb
spec/controllers/execution_environments_controller_spec.rb
spec/lib/runner/strategy/poseidon_spec.rb
spec/models/execution_environment_spec.rb
spec/models/runner_spec.rb

This MR:
* Allows editing execution environments even when they didn't exist yet in the runner management
* Implements the `environments` and `delete_environment` methods for all strategies
* Ensures that execution environments are in sync at the runner management after failed edits

Sync execution environments

---

lib/runner/strategy/poseidon.rb
spec/lib/runner/strategy/poseidon_spec.rb

This MR implements a workaround for https://github.com/openHPI/poseidon/issues/42

Poseidon: Use absolute path to remove workspace directory

---

app/assets/javascripts/dashboard.js
app/helpers/admin/dashboard_helper.rb
app/views/admin/dashboard/show.html.slim
config/locales/de.yml
config/locales/en.yml
lib/runner/strategy/docker_container_pool.rb
lib/runner/strategy/poseidon.rb
spec/helpers/admin/dashboard_helper_spec.rb

This PR will add a new column to the admin dashboard and show dedicated information for idle and used runners. Requires:
- https://github.com/openHPI/dockercontainerpool/pull/140
- https://github.com/openHPI/poseidon/pull/62
Screenshot: [Dashboard.pdf](https://github.com/openHPI/codeocean/files/7664158/Dashboard.pdf)

Adapt Dashboard to Show Idle and Used Runners

---

app/models/execution_environment.rb

@KlausGPaul Please have a look at whether this information fixes the issue you're facing in the seed step: 
It is probably related to the sample config in `code_ocean.yml`. The config listed there probably does not work well with the Vagrant setup yet. You might want to try the following there:
```yml
runner_management:
enabled: true
strategy: docker_container_pool
url: http://127.0.0.1:7100
unused_runner_expiration_time: 180
```
As of now, we have two potential backends for running submissions: Poseidon and DockerContainerPool. So far, the Vagrant setup uses the DockerContainerPool environment while the default config includes the settings for Poseidon.
Furthermore, the issue fixed with this PR will allow updating and editing an execution environment without a valid Runner management.

Check Runner management status in execution environment updates

---

lib/runner/strategy/poseidon.rb

After [Poseidon#76](https://github.com/openHPI/poseidon/issues/76) has been merged, we can remove the temporary workaround for [Poseidon#54](https://github.com/openHPI/poseidon/issues/54).

Remove Temporary Fix for Early HTTP Response from Poseidon

---

app/controllers/submissions_controller.rb
app/models/execution_environment.rb
app/models/submission.rb
app/models/testrun.rb
app/models/testrun_execution_environment.rb
db/migrate/20220415125948_add_testrun_execution_environment.rb
db/schema.rb
lib/aws_study.rb
lib/user_group_separator.rb

This issue adds support for https://github.com/openHPI/poseidon/issues/100 to CodeOcean.
It prepares an A/B test for using AWS lambda functions with CodeOcean for Java exercises in an upcoming student programming course. Those exercises running in Java 8 as part of the Java2020 course (which is the basis for the Java programming courses 2022) are suitable for the experiment and might be moved to AWS. Furthermore, it persists the execution environment used for an upcoming analysis.
Reviewing commit-by-commit is recommended.

Prepare AWS Experiment

---

lib/runner/connection/buffer.rb

Allow `\r\n` and `\n` line breaks for `Connection::Buffer`
* Nomad sends CRLF-separated lines
* AWS sends LF-separated lines
Closes https://github.com/openHPI/poseidon/issues/121

Fix linebreak for AWS

---

app/assets/javascripts/editor/editor.js.erb
app/assets/javascripts/editor/execution.js
app/controllers/execution_environments_controller.rb
app/controllers/submissions_controller.rb
app/errors/runner/error.rb
app/models/application_record.rb
app/models/runner.rb
app/models/submission.rb
app/models/testrun.rb
app/models/testrun_message.rb
app/views/exercises/external_users/statistics.html.slim
app/views/request_for_comments/show.html.slim
db/migrate/20220415215112_migrate_testruns.rb
db/schema.rb
lib/runner/strategy.rb
lib/runner/strategy/docker_container_pool.rb
lib/runner/strategy/null.rb
lib/runner/strategy/poseidon.rb
spec/models/runner_spec.rb

This MR:
- Adds additional information (exit code and execution status) to the testrun table
- Proposes a new store for log output (with the intention to replace the output column in the test run table)
- Includes a migration script for all existing outputs.
- Save detailed TestrunMessages for new code executions
- Limit output saved in TestrunMessages
- Tested migration script on staging
Missing parts once the migration is finished (another PR):
- Remove duplicated saving of output
- Remove unused enums for TestrunMessages
Closes https://github.com/openHPI/poseidon/issues/100

Refactor testrun table

---

app/controllers/exercises_controller.rb
app/views/exercises/external_users/statistics.html.slim
config/locales/de.yml
config/locales/en.yml
spec/controllers/exercises_controller_spec.rb
spec/features/external_user_statistics_spec.rb

Add option to limit exercise statistics to user-interactions #1300
When in the statistics view of a certain exercise you can now toggle all autosave submissions on and off. There is also a label indicating the status of the current state to make it more user friendly.

#1300 option to limit exercise statistics

---

app/controllers/exercises_controller.rb
app/policies/exercise_policy.rb
app/views/exercises/external_users/statistics.html.slim
config/locales/de.yml
config/locales/en.yml
config/routes.rb
spec/controllers/exercises_controller_spec.rb

This PR:
- is based on [this review comment](https://github.com/openHPI/codeocean/pull/1303#pullrequestreview-1044832274)
- keeps the same behaviour implemented for #1300
- refactors the `ExerciseController#statistics` method to be separated into two parts (one of the general exercise statistics and one for a specific user who solved the given exercise)
- does not yet tackle the large number of instance variables passed to the view (most code is just moved)

Refactor external_user_statistics to own controller action

---

app/controllers/application_controller.rb
app/mailers/user_mailer.rb
app/models/authentication_token.rb
app/models/user.rb
config/locales/de.yml
config/locales/en.yml
db/migrate/20220721131946_create_authentication_tokens.rb
db/schema.rb
spec/factories/authentication_token.rb
spec/features/authentication_spec.rb
spec/mailers/user_mailer_spec.rb

Regarding issue: Add authentication token to RfC mails #1301
Via token authentication it is now possible to view a Request for Comment even when not logged in.
Closes #1301

Rfc authentication

---

app/controllers/comments_controller.rb
spec/controllers/comments_controller_spec.rb
spec/factories/request_for_comment.rb

Regarding issue: Changing the file of a comment should not be possible #876
Added strong params to comments_controller to prevent users from editing attributes which are not intended to be edited, also created specs to test this behaviour.
Closes #876

Safe Comment Params

---

app/controllers/exercises_controller.rb
app/controllers/submissions_controller.rb
app/models/exercise.rb
app/policies/exercise_policy.rb
spec/controllers/exercises_controller_spec.rb
spec/features/editor_spec.rb
spec/models/exercise_spec.rb
spec/policies/codeharbor_link_policy_spec.rb
spec/policies/execution_environment_policy_spec.rb
spec/policies/exercise_policy_spec.rb
spec/policies/external_user_policy_spec.rb

Regarding issue: Disable / Hide score button if no tests are available #256
Added functionality that if an exercise has no tests, the score button is now disabled.
closes #256

Disable score button

---

app/controllers/execution_environments_controller.rb
app/models/execution_environment.rb
app/views/execution_environments/_form.html.slim
app/views/execution_environments/index.html.slim
app/views/execution_environments/show.html.slim
config/locales/de.yml
config/locales/en.yml
db/migrate/20220923214003_add_privileged_execution_to_execution_environment.rb
db/schema.rb
lib/runner/strategy/poseidon.rb
spec/factories/execution_environment.rb
spec/lib/runner/strategy/poseidon_spec.rb
spec/models/execution_environment_spec.rb

_Part of https://github.com/openHPI/poseidon/pull/215 and https://github.com/openHPI/dockerfiles/pull/23_
This PR introduces a new flag to control the Linux user executing the learners' source code. It is disabled by default for enhanced security.
I successfully tested the change locally (where I changed the flag in-between) with the newest version of Poseidon:

Add privilegedExecution flag to database and Poseidon strategy

---

lib/runner/strategy/poseidon.rb

This allows to protect copied files while additionally allowing learners to add new files in copied subdirectories.
Relates to https://github.com/openHPI/poseidon/pull/240

Explicitly copy folders before adding files

---

lib/runner/connection.rb

As a link says more than 1000 words, have a look [here](https://codeocean.sentry.io/performance/codeocean:95ec2d16cb3248dca12d40bae039724f/?breakdown=none&environment=development&project=5667283&query=http.method%3AGET&showTransactions=p95&sort=-transaction.duration&statsPeriod=24h&transaction=SubmissionsController%23run) 😁 
An old trace without the additional instrumentation is listed [here](https://codeocean.sentry.io/performance/codeocean:8fca428ace36487ebe98917358239302/?environment=production&project=5667283&query=http.method%3AGET+tags%5Btransaction%5D%3ASubmissionsController%23run&referrer=performance-transaction-summary&statsPeriod=24h&transaction=SubmissionsController%23run&unselectedSeries=p100%28%29) for example.
The new part are:
1. Sending the Sentry headers for the WebSocket …

Enable Sentry instrumentation for WebSocket connection

---

.rubocop_todo.yml
app/controllers/submissions_controller.rb
app/models/linter_check_run.rb
app/models/testrun_message.rb
spec/controllers/submissions_controller_spec.rb

Follow-up for #1536 and #1543 
So far, we missed the Sentry instrumentation for score and test runs. See an [old example](https://codeocean.sentry.io/performance/codeocean:e3ff4e7cca03447ba8b502866ae70a15/?environment=production&project=5667283&query=&statsPeriod=7d&transaction=SubmissionsController%23score#span-644dc77b41ac1b2e) and a [new example](https://codeocean.sentry.io/performance/codeocean:4e01343ac3dc482598a49303031f9a42/?project=5667283&query=server_name%3ASebastians-MBP&referrer=performance-transaction-summary&showTransactions=recent&statsPeriod=7d&transaction=SubmissionsController%23score&unselectedSeries=p100%28%29).
If I checked the other spans right, this should be the last one where we miss a lot of instrumentation. I also fixed one bug that occurred recently.

More Sentry monitoring and bug fixes

---

app/controllers/submissions_controller.rb
app/errors/runner/error.rb
app/models/runner.rb
lib/runner/connection.rb
spec/controllers/submissions_controller_spec.rb

Related to https://github.com/openHPI/poseidon/issues/397, this PR adds dedicated handling for the OutOfMemory errors that might occur with Poseidon and gVisor.

Handle OutOfMemory runner errors with gVisor

---

app/controllers/concerns/file_conversion.rb

With [CODEOCEAN-RQ](https://codeocean.sentry.io/issues/4383437157), we noticed odd behavior on Sentry, where the SQL connection was abnormally closed. Even though we searched for a potential root cause extensively, none could be identified. Therefore, we refactored the method in question to avoid an unnecessary `SELECT *` query.
While we are not sure that the refactoring will resolve the issue, it is our next step to try. Afterward, we will continue observing the issue.

Refactor conversion of Files JSON for download

---

app/assets/javascripts/channels/synchronized_editor_channel.js
app/assets/javascripts/editor/editor.js.erb
app/channels/application_cable/connection.rb
app/channels/synchronized_editor_channel.rb
app/policies/application_policy.rb
app/policies/programming_group_policy.rb
app/views/exercises/_editor.html.slim
lib/pair_programming23_study.rb
spec/policies/programming_group_policy_spec.rb

What does this change?
* Use Action Cable to send changes in editor to programming group team members
* Changes are displayed in the editor so that all members of a programming group see the same written code
Decisions/Choices I made:
* Client side decision if changes are own changes or from team members instead of server side decision
- In the case of a server-side decision the changes are send to all members of a programming group except one self. For that a new channel for each team member with the server is needed. Therefore, the decision was made that the work is done on client side to reduce the number of channels.

Synchronize text in editor

---

app/assets/javascripts/editor/editor.js.erb
app/models/event/synchronized_editor.rb

* Allow empty lines for current_content event: fixes CODEOCEAN-VR
* Return if editor is null: fixes CODEOCEAN-FRONTEND-3A

Fix sentry issues for pair programming

---

app/controllers/sessions_controller.rb
app/controllers/user_exercise_feedbacks_controller.rb
app/helpers/action_cable_helper.rb
app/models/code_ocean/file.rb
app/models/comment.rb
app/models/exercise.rb
app/models/request_for_comment.rb
app/models/submission.rb
app/models/user.rb
app/views/request_for_comments/_list_entry.html.slim
app/views/request_for_comments/index.html.slim

This PR adds the possibility to redirect learners to LimeSurvey (coming from LTI).
Further, this PR adds some general associations in the first commit (unrelated to the survey redirect, but required for the parameters added).
⚠️ I have tested the implementation only roughly, so please do that as part of the review.

Add custom redirect to LimeSurvey through LTI

---

app/controllers/programming_groups_controller.rb
app/helpers/statistics_helper.rb
app/models/exercise.rb
app/models/programming_group.rb
app/models/programming_group_membership.rb
app/models/request_for_comment.rb
app/models/user.rb
app/policies/exercise_policy.rb
app/policies/programming_group_policy.rb
app/views/application/_breadcrumbs_and_title.html.slim
app/views/application/_navigation.html.slim
app/views/exercises/index.html.slim
app/views/exercises/show.html.slim
app/views/programming_groups/_form_edit.html.slim
app/views/programming_groups/edit.html.slim
app/views/programming_groups/index.html.slim
app/views/programming_groups/show.html.slim
app/views/request_for_comments/index.html.slim
app/views/submissions/index.html.slim
app/views/submissions/show.html.slim
config/locales/de.yml
config/locales/en.yml
config/routes.rb
db/migrate/20181129093207_drop_errors.rb
spec/controllers/programming_groups_controller_spec.rb
spec/policies/exercise_policy_spec.rb
spec/policies/programming_group_policy_spec.rb

* Add an index route for programming groups to have an overview for admins which groups exist
* Add an destroy route for programming groups to delete groups and make it possible to start working with another person on a exercise or work alone
* Add edit & update route for programming groups to remove users from a group
* closes #1848

Create index, destroy, show, edit and update route for programming groups

---

app/assets/javascripts/editor/editor.js.erb
app/assets/javascripts/editor/evaluation.js
app/assets/javascripts/shell.js
app/controllers/execution_environments_controller.rb
app/controllers/live_streams_controller.rb
app/controllers/remote_evaluation_controller.rb
app/controllers/request_for_comments_controller.rb
app/controllers/submissions_controller.rb
app/errors/runner/error.rb
app/models/execution_environment.rb
app/models/programming_group.rb
app/models/runner.rb
app/models/testrun.rb
config/locales/de.yml
config/locales/en.yml
db/migrate/20231029172331_add_reserved_until_to_runners.rb
db/schema.rb
spec/factories/runner.rb
spec/models/execution_environment_spec.rb
spec/models/runner_spec.rb

Previously, the same runner could be used multiple times with different submissions simultaneously. This, however, yielded errors, for example when one submission time oud (causing the running to be deleted) while another submission was still executed.
Admin actions, such as the shell, can be still executed regardless of any other code execution.
Fixes CODEOCEAN-HG
Fixes openHPI/poseidon#423

Exclusively lock Runners during code executions

---

app/assets/javascripts/editor/execution.js
lib/runner/connection.rb

Recently, we noticed that Poseidon's WebSocket spans shown in Sentry are not correctly aligned with the outgoing WebSocket request in CodeOcean. This PR aims to fix that problem.
[Here's a sample trace with the code of this branch](https://codeocean.sentry.io/performance/codeocean:087ae8ca52084d06a5e25021bf7cc144/). 
Related to https://github.com/openHPI/poseidon/issues/438

Fix Sentry span for outgoing WebSocket connections

---

app/assets/javascripts/pagedown/markdown.editor.js.erb
app/helpers/application_helper.rb
app/models/submission.rb

Kramdown uses curved quotation marks by default, when rendering markdown to html
This changes them to be straight quotes, so they can be easily copied in code or the like.

fix kramdown using curved quotes 

---

app/assets/javascripts/exercise_collections.js
app/assets/javascripts/exercises.js

Previously, the ID and title of tips and exercises newly added to the list were gathered from the DOM. While we keep this mechanism, we ensure to escape the text before reusing it.

Escape text passed in collection sorting

---

app/models/concerns/contributor.rb
app/models/concerns/contributor_creation.rb
app/models/contributor.rb
app/models/programming_group.rb
app/models/user.rb
db/seeds.rb

During documentation of the pair programming feature, we noticed that the Contributor should be an abstract class, which is parent for the User and the ProgrammingGroup. With this commit, we perform these changes.

Extract Contributor concern as abstract class

---

lib/tasks/gdpr_delete.rake

This MR adds a rake task to delete users in compliance with GDPR. It removes all personally identifiable information (PII) from external users stored in CodeOcean.
Usage:
```script
rake gdpr:delete_users TXT=./delete_request.txt CONSUMER=openHPI
```
with `delete_request.txt`:
```text
15489bf6-c174-4920-8452-5b111e967b1b
6f1ed1e6-56c4-407e-ac88-7f81387e3f0e
b38c0c9e-f676-41dd-b7fc-ddb2fc33c8ff
5df7f9af-c54e-4811-9e86-8e80bbf82106
3d7d8bf9-63e0-42cb-b961-cbeafe8d056e
```

Add Rake task to GDPR delete users

---

spec/db/seeds_spec.rb

Otherwise, invoking a Rake task could lead to multiple executions, which is unexpected.

Specs: Prevent Rake task from being executed twice

---

lib/runner/connection/buffer.rb

The PyLint output is marking the erroneous location visually by using ^ in the next line. This indicator is always prefixed by multiple spaces and the line does not contain any further text. Now, it might happen that the indicator is between two source lines that use the same quote type. Since we detect quotes through our regex, this occurrence would qualify, effectively enquoting the linter indicator ^. As a consequence of our quote handling, we normally prevented quoted text from being split. However, in the described scenario, this is not desired, since we are not dealing with a regular quote (but an accidental mismatch).
Therefore, with this commit, we disable our quote handling for those multi-line quotes where one line fully represents a typical PyLint indicator line. This should …

Connection::Buffer: Ignore linter indicator accidentally wrapped in quotes

---

yarn.lock

> Browserslist: caniuse-lite is outdated. Please run: npx update-browserslist-db@latest Why you should do it regularly: https://github.com/browserslist/update-db#readme

Update caniuse-lite browser list

---

app/assets/stylesheets/request-for-comments.css.scss

When writing a comment with Python code, the indention was lost (see the [course forum](https://open.hpi.de/courses/pythonjunior-schule2024/question/ad8dcaf7-b515-4783-a066-a442e7c5786a)). This PR fixes that behavior:
| <img width="494" alt="Bildschirmfoto 2024-04-18 um 17 39 51" src="https://github.com/openHPI/codeocean/assets/7300329/df16ca40-7246-4598-a44a-21b01255a583"> | <img width="494" alt="Bildschirmfoto 2024-04-18 um 17 40 04" src="https://github.com/openHPI/codeocean/assets/7300329/2e875894-9217-4e70-8b88-954c09a35966"> |

RfC: Keep indention when displaying comments

---

app/views/exercises/implement.html.slim

Regresses 9a9efd5c and a7fa9b5b
| <img width="1728" alt="Bildschirmfoto 2024-04-24 um 16 23 24" src="https://github.com/openHPI/codeocean/assets/7300329/2bc85dfd-a72a-4186-85bb-1590aa81783c"> | <img width="1725" alt="Bildschirmfoto 2024-04-24 um 16 23 43" src="https://github.com/openHPI/codeocean/assets/7300329/3cf64015-0339-4524-a83e-4a69a4411060"> |

Fix layout for exercise description on implement route

---

app/assets/javascripts/channels/synchronized_editor_channel.js

Previously, ProgrammingGroups could have been undefined in rare cases. Therefore, we check whether the variable is properly defined before calling the method.
Fixes [CODEOCEAN-FRONTEND-7D](https://codeocean.sentry.io/issues/5237549093/)

Fix race condition on JavaScript initializer

---

app/assets/javascripts/editor/editor.js.erb

Fixes [CODEOCEAN-FRONTEND-69](https://codeocean.sentry.io/issues/5098169894/)

Fix missing linter results caused by incorrect JS loop

---

app/models/runner.rb

This is a regression from 27f128ad.
Fixes [CODEOCEAN-12R](https://codeocean.sentry.io/issues/5248673115/)

Fix NameError on block forward

---

app/controllers/concerns/lti.rb
app/controllers/sessions_controller.rb
config/locales/de.yml
config/locales/en.yml
spec/controllers/sessions_controller_spec.rb

Recently, a new institution joined CodeOcean and used a relative URL. This won't work, so that we are rejecting non-absolute URLs by now.

Enforce valid lis_outcome_service_url

---

app/assets/javascripts/base.js
app/assets/javascripts/request_for_comments.js
app/javascript/application.js
app/javascript/stylesheets.scss
config/initializers/content_security_policy.rb
config/initializers/permissions_policy.rb
config/webpack/webpack.config.js

This PR changes the way we integrate ACE, aiming to allow the web workers spawned by the editor.
Further, it adjusts the CSP and Feature Policy to current values.
This PR is already compatible with #2242.

Adjust CSP and fix ACE integration

---

app/views/application/_navigation.html.slim

This PR fixes a visual issue with the "Administration" menu alignment on smaller screens.
| <img width="376" alt="Bildschirmfoto 2024-05-08 um 10 59 38" src="https://github.com/openHPI/codeocean/assets/7300329/d5aef2a9-79b4-4ee0-97a4-a0d6ff6c1fb1"> | <img width="376" alt="Bildschirmfoto 2024-05-08 um 10 59 55" src="https://github.com/openHPI/codeocean/assets/7300329/44d17217-b929-4cfb-8240-1fe298b0d2b2"> |

Fix margin for "Administration" menu on small screens

---

.github/workflows/ci.yml

Forked repos may not have any write permissions, and thus may not write status checks for PRs. Therefore, we disable uploading slim-lint results to GitHub checks for forks. The pass/fail information is still displayed.

Fix permission issue for slim-lint CI on forks

---

app/assets/javascripts/application.js
app/assets/javascripts/channels/synchronized_editor_channel.js
app/assets/javascripts/editor/editor.js.erb
config/initializers/assets.rb
lib/code_ocean/config.rb
lib/runner/strategy/docker_container_pool.rb
spec/lib/code_ocean/config_spec.rb

This PR aims to fix another JavaScript error shown in Sentry: [CODEOCEAN-FRONTEND-7W](https://codeocean.sentry.io/issues/5276691444/).
The error indicates that `CodeOceanEditorEvaluation is not defined` in the following location:
https://github.com/openHPI/codeocean/blob/7d5883acc4f8a7af8a105fabdbd99410b7673e2a/app/assets/javascripts/editor.js#L1-L14
I was surprised by this error and have never seen it before. Still, it is similar to [CODEOCEAN-FRONTEND-7D](https://codeocean.sentry.io/issues/5237549093/) fixed in #2270. Thus, I started to reflect on why that happens and what could be the issue. 
One idea I got is linked to the recent changes we made with JavaScript assets: We changed how the ACE editor and the Markdown editor were included, removing them from Sprockets (and its general …

Change order of Sprocket assets and introduce dependency

---

app/policies/community_solution_policy.rb
spec/policies/community_solution_policy_spec.rb

Viewing the index page for community solutions was broken, since the breadcrumbs tried to access the `show?` policy.

Explicitly state permissions for CommunitySolutionPolicy

---

app/assets/javascripts/editor/execution.js

The code previously used was only working with the patched Sentry method, not when Sentry was inactive. Since a Websocket is inheriting from EventTarget, the method signature usually requires two arguments.
See https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener

Fix removal of event listeners for runSocket

---

app/assets/javascripts/editor/editor.js.erb

Otherwise, the events might be captured as:
```js
{
currentTarget: [object WebSocket],
isTrusted: true,
target: [object WebSocket],
type: error
}
```

Convert errors captured with Sentry to JSON

---

app/assets/javascripts/editor/editor.js.erb

With the current implementation, some errors were captured twice (or only a single time, even if not desired at all).
The special WebSocket errors are not nicely captured here:
Further, they lacked a complete stack trace:
Therefore, we delegate this to a dedicated method `showWebsocketError` already capturing Sentry events:
https://github.com/openHPI/codeocean/blob/c5518bb592aa47650db29ed2cc5b8e1862853dab/app/assets/javascripts/editor/editor.js.erb#L895-L905
Regularly, we disable this error tracing, i.e., when closing the connection.
https://github.com/openHPI/codeocean/blob/c5518bb592aa47650db29ed2cc5b8e1862853dab/app/assets/javascripts/editor/evaluation.js#L144
Still, with the current implementation, a (misleading) error would still be captured a single time in Sentry.

Prevent duplicate error handling for WebSocket events

---

app/assets/javascripts/editor/editor.js.erb
package.json
yarn.lock

This change is based on a suggestion by Sentry staff. It requires SDK version > 8.4.0, which is not yet released.
https://github.com/getsentry/sentry-javascript/issues/12116#issuecomment-2132812315   
https://github.com/getsentry/sentry-javascript/pull/12138

Refactor `newSentryTransaction` to use improved API

---

app/assets/javascripts/editor/editor.js.erb

Using the JSON representation of the error only works for some errors, whereas others are simply marked with a {}. Still, we attach the JSON representation to the Sentry event captured.

Capture non-JSON error in newSentryTransaction

---

.github/workflows/ci.yml

In [this action run](https://github.com/openHPI/codeharbor/actions/runs/9321858461/job/25661891189), I learned that the current setup would not upload slim-lint results, since the slim-lint job previously failed. This PR fixes that erroneous behavior.
When applying this PR, the annotations work as expected:

Ensure slim-lint annotations are always uploaded in the main repo

---

app/views/exercises/_file_form.html.slim

It seems like we mixed up two translations while working on #2248. With this PR, we fix the erroneous labels.

Fix incorrect translation on exercise edit

---

spec/rails_helper.rb
spec/spec_helper.rb

While working on https://github.com/openHPI/codeharbor/pull/1463, I noticed some differences between CodeOcean and CodeHarbor. This PR aligns both code bases again with each other.

Reorder includes for `spec_helper` and `rails_helper`

---

spec/controllers/submissions_controller_spec.rb

The explicit call to `Rails.application.routes.url_helpers` is not needed and thus removed.

Remove redundant url_helpers in spec

---

app/javascript/rails_admin.js
app/javascript/rails_admin.scss
config/initializers/rails_admin.rb
package.json
yarn.lock

Resolves an issue with a strict CSP disabling inline `data` images. With Shakapacker and our current webpack config, we extract inline `data` images to dedicated files, thus resolving the issue.

Migrate RailsAdmin assets to Shakapacker

---

app/helpers/application_helper.rb

These backlinks don't work reliably and are thus more harmful than useful.

Disable footnote backlinks in Markdown

---

db/migrate/20140826073318_sorcery_core.rb
db/migrate/20140918063522_add_hashed_content_to_files.rb
db/migrate/20150204080832_add_pool_size_to_execution_environments.rb
db/migrate/20150317083739_add_memory_limit_to_execution_environments.rb
db/migrate/20150317115338_add_network_enabled_to_execution_environments.rb
db/migrate/20160630154310_add_submission_to_request_for_comments.rb
db/migrate/20170403162848_set_default_for_request_for_comment_solved.rb
db/migrate/20170830083601_add_cause_to_testruns.rb
db/migrate/20180130172021_add_reached_full_score_to_request_for_comment.rb
db/migrate/20181119161514_add_user_to_proxy_exercise.rb
db/migrate/20181126163428_add_user_type_to_remote_evaluation_mappings.rb
db/migrate/20201019090123_add_normalized_score_and_submission_to_user_exercise_feedback.rb
db/migrate/20210602071834_change_type_of_exposed_ports_in_execution_environment.rb
db/migrate/20211114145024_create_tips_intervention.rb
db/migrate/20220415215112_migrate_testruns.rb
db/migrate/20220906142550_migrate_permissions_to_study_group.rb
db/migrate/20230206203117_migrate_filetype_extensions_not_nil.rb
db/migrate/20230819084917_unify_lti_parameters.rb
db/migrate/20230821062901_add_foreign_keys_to_anomaly_notifications.rb
db/migrate/20230821063101_convert_reason_to_json_in_anomaly_notifications.rb

This PR fixes one issue:
- It ensures we can run `db:migrate:reset` on an empty database by ensuring the model classes are specified correctly.
Further, the schema itself is fine and does not contain any major issues. There is one minor problem with the order of columns, that has not been solved yet. The current schema represents the production setup, but regenerating the schema for an empty database yields a slightly different order. For now, I did not touch this (since it worked previously without any problem).
_PS: While the migrations can now run successfully, I have not validated or touched them. Probably, some could have been designed better._

Fix missing/incorrect Model specifications in migrations

---

app/models/code_ocean/file.rb

Without this fix, `hidden_feedback` was only effective when `read_only` was set, too.
/cc @brry: This fixes the erroneous behavior we just observed together.

Correctly set `hidden_feedback` for inherited files

---

app/assets/javascripts/editor/participantsupport.js.erb

Previously, an error could occur when creating an RfC. The erroneous behavior was triggered with the following steps:
1. A learner is on the implement page
2. They click on another link to leave the current page
3. Before the new page opens (through Turbolinks), the "request comments" button was hit
4. Still before the new page was visible, a question was entered and the RfC was submitted.
5. The new page opens
6. Creating the RfC was successful, and a code run should be triggered (as well as hiding the question modal etc.)
With this commit, we still allow creating an RfC without error even if the page was left before everything finished.
Fixes [CODEOCEAN-FRONTEND-9C](https://codeocean.sentry.io/issues/5410402406/)

Prevent error during RfC create when navigating

---

app/controllers/concerns/lti.rb
app/controllers/sessions_controller.rb
app/helpers/authenticated_url_helper.rb
app/views/sessions/destroy_through_lti.html.slim
config/locales/de/session.yml
config/locales/en/session.yml
spec/concerns/lti_spec.rb
spec/controllers/sessions_controller_spec.rb
spec/factories/lti_parameter.rb
spec/helpers/authenticated_url_helper_spec.rb
spec/views/sessions/destroy_through_lti.html.slim_spec.rb

This PR fixes multiple smaller issues with LTI launch requests. It mainly improves two aspects:
- It shows more error details in case of a rejected launch request.
- The `launch_presentation_return_url` is also validated (similar to `lis_outcome_service_url` added in #2275) and now considered optional
Besides these aspects, the PR tackles other, minor issues. Therefore, reviewing commit-by-commit is recommended.

Improve error handling for LTI sessions

---

app/policies/code_ocean/file_policy.rb
app/policies/codeharbor_link_policy.rb
app/policies/programming_group_policy.rb

Despite having a dedicated `no_one` method, it wasn't consequently used in all places. Thus, this PR re-aligns the usage across all policies.
//cc @Melhaya for the boy scouting rule
_PS: The tests are failing until #2398 has been merged._

Policy: Use no_one rather than false

---

app/views/application/help.html.slim
app/views/exercises/implement.html.slim
config/locales/de/execution_environment.yml
config/locales/de/exercise.yml
config/locales/de/meta/shared.yml
config/locales/en/execution_environment.yml
config/locales/en/exercise.yml
config/locales/en/meta/shared.yml

We recently noticed that our links to external pages only contained the `noopener` directive (instructing browsers to use a dedicated context for the new target) but not the `noreferrer` (which hides the source page's address from the new page). This PR fixes said behavior.
//cc @Melhaya for the boy scouting rule
_PS: The tests are failing until #2398 has been merged._

Add noreferrer policy for external links

---

app/views/exercises/external_users/statistics.html.slim
app/views/external_users/statistics.html.slim
config/locales/de/exercise.yml
config/locales/de/external_user.yml
config/locales/en/exercise.yml
config/locales/en/external_user.yml
spec/views/exercises/external_users/statistics.html.slim_spec.rb

While working on my research, I noticed an imprecise localization for statistics, giving too few context.
//cc @Melhaya for the boy scouting rule
_PS: The tests are failing until #2398 has been merged._

Improve locales for external user statistics

---

app/views/application/help.html.slim
app/views/programming_groups/_info_pair_programming.html.slim

Previously, the content for a modal footer was concatenated (which was unintended). Now, each modal as its own footer, if configured.
| ![Bildschirmfoto 2024-08-02 um 14 36 08](https://github.com/user-attachments/assets/0c5a09ff-c95a-445c-86f3-9c21485a678d) ![Bildschirmfoto 2024-08-02 um 14 36 34](https://github.com/user-attachments/assets/94634afa-9824-4a9b-acdc-d40b33fff502) | ![Bildschirmfoto 2024-08-02 um 14 36 27](https://github.com/user-attachments/assets/33c1f544-c5d1-4c13-bc6f-44588d69ae22) ![Bildschirmfoto 2024-08-02 um 14 36 34](https://github.com/user-attachments/assets/94634afa-9824-4a9b-acdc-d40b33fff502)  |

Flush content for modal footer

---

app/controllers/exercises_controller.rb
app/views/exercises/external_users/statistics.html.slim

Previously, hiding autosaves also mixed up with the calculation of working times. This was caused by the missing submissions not being reflected in the deltas. The solution implemented here is not nice, but fulfills its requirements. Refactoring of the whole view is recommended.
| With Autosaves | Before | After |
|--------|--------|--------|
| <img width="714" alt="Bildschirmfoto 2024-08-09 um 13 26 14" src="https://github.com/user-attachments/assets/c0abc7c0-40ea-4db8-94bb-f8d02310531c"> | <img width="709" alt="Bildschirmfoto 2024-08-09 um 13 26 27" src="https://github.com/user-attachments/assets/44f01a2d-ec31-4cff-9864-f53a34f36d8f"> | <img width="712" alt="Bildschirmfoto 2024-08-09 um 13 26 36" src="https://github.com/user-attachments/assets/185cfbd5-1952-4065-bdf3-fae32cd7e3be"> |

Fix working time statistics when viewed without autosaves

---

.rubocop/rails.yml
app/models/user.rb
app/policies/consumer_policy.rb
app/policies/exercise_policy.rb
app/policies/external_user_policy.rb
app/policies/internal_user_policy.rb
app/policies/programming_group_policy.rb
app/policies/proxy_exercise_policy.rb
app/policies/submission_policy.rb

Previously, the subquery (for the study group IDs) was performed for each row during the join operation. Especially joining the submission table was too expensive for that operation, causing a massive slowdown. The metric below is already showing a subsequent query (with a fully loaded cache pipeline), the first request even took longer.
I feel there would be more potential to improve the page rendering even further, but this is out of scope for now. Affected are only teachers, since admins don't have the respective study group filter.
| <img width="1475" alt="Bildschirmfoto 2024-08-05 um 21 15 31" src="https://github.com/user-attachments/assets/f239af40-3913-451a-8e12-d715b6923a59"> | <img width="1474" alt="Bildschirmfoto 2024-08-05 um 21 30 42" …

Use memorized study groups for Pundit Scopes

---

app/controllers/study_groups_controller.rb

Previously, the wrong parameter prevented correct updates to the group when an internal user was present. Now, we can handle validation errors of the StudyGroup as intended and remove both, internal and external users.
Fixes [CODEOCEAN-13X](https://codeocean.sentry.io/issues/5698367654/)

Allow updates to StudyGroups with internal users

---

app/models/runner.rb
app/models/user.rb
spec/support/runner.rb

Previously, a boolean value of `false` would not have been memorized correctly. Instead, the mechanism commonly used with `||=` would always reevalute the original, rendering the memorization useless. `true` values were not affected of this bug.

Fix memorization for false values

---

app/controllers/internal_users_controller.rb
config/environments/development.rb
config/environments/test.rb
spec/controllers/code_ocean/files_controller_spec.rb
spec/controllers/comments_controller_spec.rb
spec/controllers/consumers_controller_spec.rb
spec/controllers/execution_environments_controller_spec.rb
spec/controllers/exercises_controller_spec.rb
spec/controllers/internal_users_controller_spec.rb

So far, we had a few tests (and production-used code) that would log unpermitted parameters. This PR therefore addresses this issue by ensuring we are not sending unpermitted parameters during regular use. Furthermore, it raises if any unpermitted parameter is detected in development or test to make everyone aware.
As an additional extra, this PR also reorders some methods for the `InternalUsersController`.

Remove any unpermitted parameters and raise if it reoccurs

---

spec/support/expectations.rb

We want to ensure that RSpec expectations are used correctly. Hence, we want to raise on potential false positives, allowing developers to double-check their expectations.

RSpec: Raise on potential false positives

---

app/helpers/application_helper.rb
app/views/exercise_collections/_form.html.slim
app/views/exercises/_editor.html.slim
app/views/exercises/_editor_file_tree.html.slim
app/views/exercises/_export_actions.html.slim
app/views/exercises/_form.html.slim
app/views/exercises/implement.html.slim
app/views/exercises/index.html.slim
app/views/exercises/show.html.slim
app/views/layouts/application.html.slim
app/views/programming_groups/_info_pair_programming.html.slim
app/views/programming_groups/new.html.slim
app/views/request_for_comments/show.html.slim
app/views/shared/_modal.html.slim
config/locales/de/exercise.yml
config/locales/de/meta/shared.yml
config/locales/de/programming_group.yml
config/locales/en/exercise.yml
config/locales/en/meta/shared.yml
config/locales/en/programming_group.yml

* Introduce `clear_content_for` method to prevent double rendering of the footer (once again, amends 092e8426).
* Use common translation for Close button

Unify modal with CodeHarbor

---

config/webpack/webpack.config.js

There were two distinct issues with source maps generated by WebPakc that prevented them to be useful. Sprocket-generated source maps were not affected.
| Bug | Before | After |
|--------|--------|--------|
| JavaScript source maps were only available in production | <img width="1840" alt="Bildschirmfoto 2024-08-30 um 22 07 36" src="https://github.com/user-attachments/assets/97bc5b29-d021-44c5-a2af-76f1fabde944"> | <img width="1840" alt="Bildschirmfoto 2024-08-30 um 22 09 48" src="https://github.com/user-attachments/assets/10d87458-4e92-41d1-887e-dd334457758b"> |
| SASS / SCSS did not have proper source files at all | <img width="1840" alt="Bildschirmfoto 2024-08-30 um 22 07 43" src="https://github.com/user-attachments/assets/abfe5d07-7c2b-46e2-b004-f7bf22aafb48"> | <img width="1840" …

Fix source map generation with Webpack

---

app/errors/runner/error.rb
lib/runner/strategy/poseidon.rb
spec/lib/runner/strategy/poseidon_spec.rb

With the extracted method it is easier to recognize the environments which caused an issue in Sentry.

Extract health check for depleted environments

---

app/models/runner.rb

Previously, a runner was not released in case of an `Runner::Error`. Especially when a runner was not found (i.e., when executing an arbitrary command), a `Runner::Error::RunnerNotFound` exception was thrown. Then, the automatic request for a new runner failed, since the previous runner was still in use.

Release runner in case of errors

---

.github/workflows/ci.yml
.gitlab-ci.yml
README.md
db/seeds.rb
docs/LOCAL_SETUP.md
docs/backup.md
spec/db/seeds_spec.rb

`db:prepare` was introduced with Rails 6 and performs the necessary steps in a multi-database Rails app to bring the database to the required state. If non-existent, a new database is created and the schema is loaded; otherwise, migrations are performed.

Replace `db:migrate` with `db:prepare`

---

app/assets/javascripts/exercises.js

Previously, any new file added to an exercises didn't feature syntax highlighting (it was only enabled for those files retrieved from the database). With this PR, we enable syntax highlighting for new exercise files, too. It doesn't matter whether only the exercise file is new or whether the whole exercise is new.

Exercise Edit: Enable syntax highlight for new files

---

app/assets/javascripts/exercises.js

While working on #2529, I noticed a few outdated JavaScript elements. Hence, this PR includes the following changes:
- `var` is replaced by `const` or `let`, except for functions
- string concatenation is replaced with string interpolation
- duplicate jQuery selectors are removed
- Use Regex character class rather than single character alternative
- JS type conversion safe comparison

Use modern JS syntax for exercises.js

---

app/assets/javascripts/editor/editor.js.erb

The previous RegEx used was pretty inefficient and could result in an "too much recursion" error. I still assume that the updated RegEx catches all relevant file names, without limiting recognition.
Fixes [CODEOCEAN-FRONTEND-9Q](https://codeocean.sentry.io/issues/5535604651/)

Improve file name extraction for Java files

---

app/controllers/concerns/lti.rb
app/controllers/sessions_controller.rb

This error could occur when a valid hostname is given, but no server is listening on the given address.
Fixes [CODEOCEAN-14K](https://codeocean.sentry.io/issues/5858077050/)

LTI: Catch `Errno::ECONNREFUSED` as error

---

.github/workflows/sentry-release.yml

Marking a new commit on master as release is required for the newly-added Ansible workflow with integrated Sentry deployment tracking. This  workflow is based on Poseidon's workflow: https://github.com/openHPI/poseidon/blob/main/.github/workflows/sentry-release.yml

Configure Sentry release Workflow for GitHub actions

---

Gemfile
Gemfile.lock
config/cable.yml
config/database.yml.example
db/cable_schema.rb
db/migrate/20240912101506_drop_action_cable_large_payloads.rb
db/schema.rb

Switching the adapter is not expected to make any noticeable difference. The previous gem used was an interim solution and is now replaced by the new Solid Cable adapter shipping with Rails 8 by default.
This PR depends on the following two PRs to be merged first:
- #2478
- #2524 
Only when those two PRs are merged, the tests in this branch will pass. Nevertheless, reviewing is already possible, @Dome-GER 😉

Add Solid Cable adapter for ActionCable

---

app/mailers/application_mailer.rb

The `default` setting within the ApplicationMailer is overwriting the previously-set values from `config/action_mailer.yml`. Of course, that is not intended and needs to be fixed.

Remove non-working default for ApplicationMailer

---

config/environments/production.rb

Otherwise, only the `id` is shown by default (in contrast to `full_inspect`). This behavior has changed with Rails 7.2, and previously showed all information by default.
Since we often use `inspect` within the application to get details about unexpected errors, we want to keep the previous behavior.

Show all attributes when inspecting an object in production

---

.gitignore

This change to the `.gitignore` is needed in conjunction with our Ansible setup.

Ignore any CA certificate if present

---

app/controllers/request_for_comments_controller.rb
app/views/shared/_form_filters.html.slim

This PR fixes two issues related to RfC searches:
- Use current path for form_filter search partial
- Fix `where` filter for `my_request_for_comments` search

Fix two issues preventing RfC searches

---

app/controllers/remote_evaluation_controller.rb
app/models/runner.rb
config/locales/de/remote_evaluation.yml
config/locales/en/remote_evaluation.yml
docs/remote_evaluation.yml
lib/code_ocean/remote-evaluation.schema.json
spec/controllers/remote_evaluation_controller_spec.rb

This PR contains two major changes, aiming to improve the robustness of usefulness of the remote evaluation:
- Add schema validation for RemoteEvaluation
- Add OpenAPI documentation for RemoteEvaluationController

Add schema validation and documentation for RemoteEvaluation

---

app/controllers/comments_controller.rb
app/controllers/request_for_comments_controller.rb
lib/tasks/detect_exercise_anomalies.rake

Now, we are only using `deliver_now` for login-based emails, such as password reset or confirmation emails.

Use `deliver_later` to send emails

---

app/controllers/concerns/redirect_behavior.rb

Previously, the counter was only changed in memory but not persisted. Rather than adding a .save call, I decided to use the bang method (despite skipping model validations). This, however, will improve the SQL query and prevent any concurrent updates that otherwise wouldn't be atomic.
The resulting SQL query is really nice:
```
UPDATE "request_for_comments" SET "times_featured" = COALESCE("times_featured", 0) + 1 WHERE "request_for_comments"."id" = $1
```

RfCs: Correctly increment `times_featured` counter

---

Gemfile
Gemfile.lock
config/initializers/monkey_patches.rb

Tubesock is outdated and should be replaced with ActionCable. For now, however, we simply patch the issues we've discovered.
I've created a custom fork, included some pending contributions and made additional suggestions.

Use openHPI-managed Tubesock fork

---

app/controllers/remote_evaluation_controller.rb
docs/remote_evaluation.yml

Especially for responses with HTTP status code 201, the Location header should be present.

Remote evaluation: Include submission as HTTP location header

---

config/initializers/prometheus.rb
lib/prometheus/controller.rb

Fixes [CODEOCEAN-157](https://codeocean.sentry.io/issues/5938482598/)

Prevent Prometheus initialization during `i18n export`

---

app/models/submission.rb

The previous mechanism always cycled through all files once again, just to identify the very same file and using an attribute passed to the method. This can be simplified with the given refactoring.

Simplify `Submission#command_for`

---

app/assets/javascripts/editor/editor.js.erb
app/assets/javascripts/editor/participantsupport.js.erb
app/assets/javascripts/exercise_collections.js
app/assets/javascripts/exercises.js
app/assets/javascripts/request_for_comments.js

There are too many edge cases where the modal might not be present any longer, and we just want to avoid unnecessary errors.

Use safe navigation operator for Bootstrap Modals

---

app/assets/javascripts/community_solution.js
app/assets/javascripts/editor/editor.js.erb
app/assets/javascripts/editor/evaluation.js
app/assets/javascripts/editor/execution.js
app/assets/javascripts/editor/participantsupport.js.erb
app/assets/javascripts/editor/submissions.js

With these changes, we prevent that a second code execution can be triggered while a first one is still running. These change applies to any form of code execution, including runs, score runs, test runs, submit requests, RfC requests.
With the changed `stopCode` function, switching from one execution mode to another (i.e., run to score or vice versa) will wait until the previous execution stopped. When the window is reloaded, either the execution stops immediately (run) or the backend lock mechanism for runners will still prevent duplicate executions (test, score, submit).
The changes in this commit further ensures that the same button cannot be pressed twice. For example, a double-click on Run would previously schedule two executions, which might interfere with each other (or simply …

Prevent simultaneous code execution requests in JavaScript

---

app/assets/javascripts/editor/websocket.js
spec/support/wait_for_websocket.rb

Previously, we used some mixed methods to identify the ready state of WebSocket connections with different methods and target states. By using the same method and enum values, we can ensure easier navigation for developers and better maintenance.

Unify comparison of the WebSocket ready state

---

.github/workflows/ci.yml

Since aligning our RSpec setup to the recommended defaults, we don't need the manual require statements any longer.

GitHub Actions: Use RSpec command without manual requires

---

app/assets/javascripts/editor/editor.js.erb
app/assets/javascripts/editor/submissions.js

When a code execution is started, we shortly show a spinner on the Run button before it changes to Stop, allowing learners to abort the current code execution. However, previously, the Stop button was shown too early namely when the WebSocket connection was getting initialized. When it was immediately pressed after becoming available, it didn't had any effect.
With the changes of this commit, we delay showing the Stop button, so that it will be shown only once the runner is actually beginning with the code execution (as indicated by the `container_running` status).

Only allow stopping the current code execution when started

---

spec/support/wait_for_ajax.rb
spec/support/wait_for_websocket.rb

The previously used approach with `Timeout.timeout` works. However, it might interrupt the `page.evaluate_script`, which will cause an unhandled exception with the Selenium webdriver which in turn crashes. Once crashed, all further Selenium-based tests will fail, too.

Selenium: Refactor WaitFor* scripts to prevent crashes

---

app/controllers/submissions_controller.rb

When a running execution is stopped by the client (through the WebSocket connection), we immediately call `close_client_connection` to terminate Tubesock connection to the browser and stop the runner. However, since the regular workflow also included a call to `close_client_connection`, it might have been called twice.

Prevent duplicate close of client connection

---

app/models/submission.rb

Previously, many different executions got all files despite not necessary needed. We now extend the file filtering to apply for submit actions, remote evaluations and test executions, too.

Improve file filtering for submission execution

---

app/controllers/submissions_controller.rb
lib/runner/connection.rb

The previous code mostly worked but there could be cases where stopping was delayed. This is especially problematic with the reservation of runners, since they could still be reserved (internally) without a visual indicator for the learners.
The change in the SubmissionsController is optional, since a browser should also close the connection once `close_client_connection` is executed. However, this change might stop the runner earlier, which is especially useful in case of infinite loops.

Immediately close a WebSocket connection to a runner

---

app/models/runner.rb
app/models/submission.rb

This commit changes how runners are reserved and released. Previously, a runner was reserved only for the actual time it was actively used and the aim was to reserve it for a time as short as possible. The previous mechanism worked, but had some drawbacks:
For example, a learner could start a submission scoring, which would perform (1) a file copy, (2) an execution of the first test file, (3) an execution of the second test file, etc. For each of these actions, the runner would be reserved and released. Now, it could happen that another run was triggered between the execution of both test files, causing issues with the remaining scoring.
In the refactored version, a runner is reserved once before initially copying files and only released after the last command finished. This ensures that …

Reserve runners for the whole duration of their use

---

app/controllers/request_for_comments_controller.rb
app/models/concerns/ransack_object.rb
app/models/exercise.rb
app/models/request_for_comment.rb
app/views/request_for_comments/index.html.slim

Without this change, we would first filter for the last 2 RfCs per record and then perform the search. Imagine, a user has three RfCs for exercises 1, 2, 3 (created in the order of the exercises). Now, when searching for open RfCs of the first exercise, the learner's RfC wasn't shown: The last_per_user would only return RfC for exercise 2 and 3, where the search term for exercise 1 would remove those two from the result set further.
With the new version, we first apply the custom filter and then limit the result set by two RfCs per learner.
We further took the opportunity to fix the broken sorting (by exercise name). The resulting code seems pretty complex, but I wasn't able to find a better, more suitable (and performant!) version.
Here are examples of the resulting SQL queries and their …

RfC Search: Apply last_per_user filter after other search terms

---

app/controllers/exercises_controller.rb
app/models/code_ocean/file.rb
app/services/proforma_service/convert_exercise_to_task.rb
app/services/proforma_service/convert_task_to_exercise.rb
app/services/proforma_service/import.rb
db/migrate/20240903204319_add_xml_path_to_files.rb
db/migrate/20241007204319_add_xml_path_to_files.rb
db/schema.rb
spec/controllers/exercises_controller_spec.rb
spec/models/code_ocean/file_spec.rb
spec/services/proforma_service/convert_exercise_to_task_spec.rb
spec/services/proforma_service/convert_task_to_exercise_spec.rb
spec/services/proforma_service/import_spec.rb

Use `xml_id_path` to recreate proforma structure with tests and model_solutions containing multiple files
also sets `xml_id_path` for exported files, if it is not set. (similiar to uuid)

Proforma: reuse existing files on import, if possible

---

spec/factories/request_for_comment.rb

Associations created by a factory need to be persisted to avoid testing against an in memory object by mistake.

Fix: Persist factory assignments of file for RfCs

---

app/services/exercise_service/push_external.rb
config/locales/de/exercise.yml
config/locales/en/exercise.yml
spec/services/exercise_service/push_external_spec.rb

Added a more descriptive error message for the presumably most common error.

1680: Improve error when exporting through an account_link

---

app/controllers/exercises_controller.rb
app/services/exercise_service/check_external.rb
spec/controllers/exercises_controller_spec.rb
spec/services/exercise_service/check_external_spec.rb

fix checking for blank UUID while importing and exporting

---

app/assets/javascripts/exercises.js
app/views/exercises/index.html.slim
config/locales/de/exercise.yml
config/locales/en/exercise.yml

- fixes bugs introduced in #2867 
- fixes incoherent use of proforma/Proforma/ProFormA/ProFormAXML

Bugfix transfer dialog header, translation unification

---

app/controllers/comments_controller.rb
app/controllers/request_for_comments_controller.rb
app/jobs/detect_exercise_anomalies_job.rb
app/mailers/user_mailer.rb
spec/mailers/previews/user_mailer_preview.rb
spec/mailers/user_mailer_spec.rb
spec/system/authentication_system_spec.rb

Related to #2959, we migrate all mailers to use parameterized attributes, since this should work better with testing.

Migrate mailers to use parametrized attributes

---

app/assets/javascripts/editor/editor.js
app/assets/javascripts/editor/participantsupport.js
app/helpers/exercise_helper.rb
app/views/exercises/_editor.html.slim
config/initializers/assets.rb

This commit reverts the changes performed in 65416934, and uses local data attributes to pass settings to the frontend.
The current solution is not ideal yet, but sufficient to continue with other important tasks.
Relates to #2964.

Migrate .js.erb files to .js

---

spec/factories/execution_environment.rb

The jRuby environment has no supported/maintained docker image.

chore: Remove unused jRuby environment

---

app/policies/comment_policy.rb
spec/policies/comment_policy_spec.rb

test: Add tests for comment policy

---

.rubocop.yml
.rubocop_todo.yml

Rubocop gives valuable information about issues in migration. New migrations should be checked by the linter.

chore: Enable Rubocop for migrations

---

lib/assets/javascripts/color_mode_picker.js

The migration event needs to be used to set the event listeners for the theme select.

fix: Theme selection event listeners

---

app/javascript/sprocket-asset-import/color-mode-picker.js

The `tubo:load` event is faster than the migration event. The color changing requires no sprocket code and can be controlled without the migration event. This removes the flickering in dark mode when navigating the page.
This change is possible because the theme-changing logic was moved to Webpacker and loads before Sprockets. Please see #3025
Related to #3040

fix: Faster theme loading to avoid flickering
